'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Building2, Check, Loader2, Mail, MapPin, Phone } from 'lucide-react';
import { FaqAccordion } from '@/components/faq/FaqAccordion';
import { useToast } from '@/components/feedback/ToastProvider';

const steps = ['İşletme', 'İletişim', 'Faaliyet', 'Onay'];
const applicationFaq = [
  ['Başvurum ne kadar sürede sonuçlanır?', 'Başvurular yönetim ekibi tarafından sırayla incelenir. Sonuçlandığında aktif karakterinize bildirim gönderilir.'],
  ['Onaylanan başvuru hemen ilan yayınlayabilir mi?', 'Başvuru onayı mağazanızı oluşturur. Kurumsal ilan yayınlamak için ayrıca aktif bir kurumsal üyelik ve kullanılabilir ilan hakkı gerekir.'],
  ['Başvurum reddedilirse tekrar başvurabilir miyim?', 'Ret gerekçesini kurumsal panelinizden inceleyebilir, işletme bilgilerinizi düzelttikten sonra uygun olduğunda yeniden başvuru yapabilirsiniz.'],
] as const;

export default function CorporateApplicationWizardPage() {
  const router = useRouter();
  const { showToast } = useToast();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({ companyName: '', contactPhone: '', contactEmail: '', location: '', purpose: '' });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const stepValid = step === 0 ? Boolean(form.companyName.trim()) : step === 1 ? Boolean(/^\d+$/.test(form.contactPhone) && form.contactEmail.trim() && form.location.trim()) : step === 2 ? form.purpose.trim().length >= 40 : true;

  const submit = async () => {
    setSubmitting(true); setError('');
    try {
      const response = await fetch('/api/dealers/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok || !data.success) throw new Error(data.error || 'Başvuru gönderilemedi.');
      showToast('Kurumsal satıcı başvurunuz alındı.', 'success'); router.replace('/hesabim/kurumsal'); router.refresh();
    } catch (err: any) { const message = err.message || 'Başvuru gönderilemedi.'; setError(message); showToast(message, 'error'); } finally { setSubmitting(false); }
  };

  return <div className="mx-auto max-w-3xl space-y-6"><Link href="/hesabim/kurumsal" className="inline-flex items-center gap-2 text-xs font-semibold text-[var(--text-muted)] hover:text-[#FF8A1F]"><ArrowLeft className="h-4 w-4" />Kurumsal panele dön</Link><div className="surface-card overflow-hidden rounded-2xl border border-[var(--border-app)]"><header className="border-b border-[var(--border-app)] p-6 sm:p-8"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-[var(--brand-orange-subtle)] text-[#FF8A1F]"><Building2 className="h-5 w-5" /></div><h1 className="text-2xl font-black text-[var(--text-main)]">Kurumsal Satıcı Başvurusu</h1><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">İşletmenizi doğrulayabilmemiz için bilgileri dört kısa adımda tamamlayın.</p></header><div className="border-b border-[var(--border-app)] px-6 py-4 sm:px-8"><ol className="grid grid-cols-4 gap-2">{steps.map((label, index) => <li key={label} className="space-y-2"><div className={`h-1 rounded-full ${index <= step ? 'bg-[#FF8A1F]' : 'bg-[var(--bg-surface-secondary)]'}`} /><span className={`hidden text-[10px] font-bold sm:block ${index === step ? 'text-[#FF8A1F]' : 'text-[var(--text-dim)]'}`}>{index + 1}. {label}</span></li>)}</ol></div><div className="min-h-[330px] p-6 sm:p-8">
    {step === 0 && <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FF8A1F]">Adım 1</p><h2 className="mt-2 text-xl font-bold text-[var(--text-main)]">İşletmenizi tanımlayın</h2></div><label className="block space-y-2"><span className="text-xs font-semibold text-[var(--text-muted)]">Şirket / galeri adı</span><input autoFocus value={form.companyName} onChange={(e) => update('companyName', e.target.value)} className="form-input text-sm" /></label></div>}
    {step === 1 && <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FF8A1F]">Adım 2</p><h2 className="mt-2 text-xl font-bold text-[var(--text-main)]">İletişim ve konum</h2></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><span className="flex items-center gap-1.5 text-xs font-semibold text-[var(--text-muted)]"><Phone className="h-3.5 w-3.5" />Telefon</span><input inputMode="numeric" pattern="[0-9]*" value={form.contactPhone} onChange={(e) => update('contactPhone', e.target.value.replace(/\D/g, ''))} className="form-input text-sm" /></label><label className="space-y-2"><span className="flex items-center gap-1.5 text-xs font-semibold text-[var(--text-muted)]"><Mail className="h-3.5 w-3.5" />SanMail / e-posta</span><input value={form.contactEmail} onChange={(e) => update('contactEmail', e.target.value)} className="form-input text-sm" /></label><label className="space-y-2 sm:col-span-2"><span className="flex items-center gap-1.5 text-xs font-semibold text-[var(--text-muted)]"><MapPin className="h-3.5 w-3.5" />İşletme konumu</span><input value={form.location} onChange={(e) => update('location', e.target.value)} className="form-input text-sm" /></label></div></div>}
    {step === 2 && <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FF8A1F]">Adım 3</p><h2 className="mt-2 text-xl font-bold text-[var(--text-main)]">Faaliyet amacını anlatın</h2></div><label className="block space-y-2"><span className="text-xs font-semibold text-[var(--text-muted)]">Faaliyet amacı ve işletme detayları</span><textarea rows={7} maxLength={1000} value={form.purpose} onChange={(e) => update('purpose', e.target.value)} className="form-input resize-none text-sm" /><span className={`block text-right text-[11px] ${form.purpose.trim().length < 40 ? 'text-[var(--text-dim)]' : 'text-emerald-400'}`}>{form.purpose.trim().length}/1000 · en az 40 karakter</span></label></div>}
    {step === 3 && <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FF8A1F]">Adım 4</p><h2 className="mt-2 text-xl font-bold text-[var(--text-main)]">Başvuruyu gözden geçirin</h2></div><dl className="grid gap-4 rounded-xl border border-[var(--border-app)] bg-[var(--bg-surface-secondary)]/35 p-5 text-sm sm:grid-cols-2"><div><dt className="text-[11px] text-[var(--text-dim)]">İşletme</dt><dd className="mt-1 font-semibold text-[var(--text-main)]">{form.companyName}</dd></div><div><dt className="text-[11px] text-[var(--text-dim)]">Konum</dt><dd className="mt-1 font-semibold text-[var(--text-main)]">{form.location}</dd></div><div><dt className="text-[11px] text-[var(--text-dim)]">Telefon</dt><dd className="mt-1 text-[var(--text-main)]">{form.contactPhone}</dd></div><div><dt className="text-[11px] text-[var(--text-dim)]">SanMail / e-posta</dt><dd className="mt-1 text-[var(--text-main)]">{form.contactEmail}</dd></div><div className="sm:col-span-2"><dt className="text-[11px] text-[var(--text-dim)]">Faaliyet amacı</dt><dd className="mt-1 whitespace-pre-wrap leading-6 text-[var(--text-main)]">{form.purpose}</dd></div></dl></div>}
    {error && <p className="mt-5 rounded-xl bg-[var(--color-danger-subtle)] p-3 text-xs font-semibold text-[var(--color-danger)]">{error}</p>}
  </div><footer className="flex items-center justify-between border-t border-[var(--border-app)] p-6 sm:px-8"><button type="button" onClick={() => setStep((value) => Math.max(0, value - 1))} disabled={step === 0 || submitting} className="btn-secondary px-4 py-2.5 text-xs disabled:opacity-40"><ArrowLeft className="h-4 w-4" />Geri</button>{step < 3 ? <button type="button" onClick={() => stepValid && setStep((value) => value + 1)} disabled={!stepValid} className="btn-primary px-5 py-2.5 text-xs disabled:opacity-40">Devam <ArrowRight className="h-4 w-4" /></button> : <button type="button" onClick={submit} disabled={submitting} className="btn-primary px-5 py-2.5 text-xs">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}Başvuruyu Gönder</button>}</footer></div><section aria-labelledby="corporate-application-faq" className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#FF8A1F]">Yardım</p><h2 id="corporate-application-faq" className="mt-2 text-xl font-black text-[var(--text-main)]">Kurumsal başvuru hakkında</h2></div><FaqAccordion items={applicationFaq} /></section></div>;
}