-- Read-only postflight. Every query must return the expected shape/count; this script mutates nothing.
SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='listing_purge_jobs' ORDER BY ordinal_position;
SELECT conrelid::regclass table_name,conname,pg_get_constraintdef(oid) definition FROM pg_constraint WHERE conrelid IN('public.listing_purge_jobs'::regclass,'public.media_cleanup_jobs'::regclass,'public.offer_threads'::regclass,'public.reports'::regclass) ORDER BY 1,2;
SELECT indexrelid::regclass index_name,pg_get_indexdef(indexrelid) definition FROM pg_index WHERE indrelid IN('public.listing_purge_jobs'::regclass,'public.media_cleanup_jobs'::regclass) ORDER BY 1;
SELECT p.proname,pg_get_function_identity_arguments(p.oid) arguments,p.prosecdef,p.proconfig,p.proacl,position('SKIP LOCKED' IN pg_get_functiondef(p.oid))>0 skip_locked FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN('canonical_sanboard_media_key','is_media_key_referenced','enqueue_media_cleanup_job','enqueue_listing_purge_job','discover_listing_purge_jobs','claim_listing_purge_jobs','retry_listing_purge_job','claim_media_cleanup_jobs','complete_media_cleanup_job','retry_media_cleanup_job','requeue_media_cleanup_job','replace_listing_images_atomic','complete_listing_purge_media_key','finalize_listing_purge')ORDER BY 1;
SELECT table_name,grantee,string_agg(privilege_type,',' ORDER BY privilege_type) privileges FROM information_schema.role_table_grants WHERE table_schema='public'AND table_name IN('listing_purge_jobs','media_cleanup_jobs')GROUP BY 1,2 ORDER BY 1,2;
SELECT 'purge' queue,status,count(*) jobs,min(next_attempt_at) oldest_ready,min(lease_until) oldest_lease FROM public.listing_purge_jobs GROUP BY status UNION ALL SELECT 'media',status,count(*),min(next_attempt_at),min(lease_until)FROM public.media_cleanup_jobs GROUP BY status ORDER BY 1,2;
SELECT count(*) FILTER(WHERE status='PROCESSING'AND lease_until<now()) expired_leases,count(*) FILTER(WHERE status IN('PENDING','RETRY')AND attempts>=max_attempts) exhausted FROM public.listing_purge_jobs;
SELECT count(*) FILTER(WHERE status='PROCESSING'AND lease_until<now()) expired_leases,count(*) FILTER(WHERE status IN('PENDING','RETRY')AND attempt_count>=max_attempts) exhausted FROM public.media_cleanup_jobs;
SELECT count(*) offer_history_missing FROM public.offer_threads WHERE original_listing_id IS NULL;
SELECT count(*) report_history_missing FROM public.reports WHERE historical_listing_id IS NULL;
SELECT count(*) payment_history_missing FROM public.payments WHERE target_listing_id IS NOT NULL AND historical_target_listing_id IS NULL;
SELECT count(*) purge_media_not_done FROM public.listing_purge_jobs j CROSS JOIN LATERAL jsonb_array_elements_text(j.media_keys)k WHERE j.status='DONE'AND NOT EXISTS(SELECT 1 FROM public.media_cleanup_jobs m WHERE m.idempotency_key='purge:'||j.id||':'||k AND m.status='DONE');
