import { IOfferRepository } from '../types';
import { getSupabaseAdminClient } from '../../supabase-client';
import { OFFER_PAGE_SIZE } from '@/lib/offers/constants';
import { OfferCloseReason, OfferThread } from '@/types';

export class SupabaseOfferRepository implements IOfferRepository {
  private client(){const c=getSupabaseAdminClient();if(!c)throw new Error('Supabase service role yapılandırılmamış.');return c;}
  private result(data:any,error:any){if(error)return{success:false,error:'Teklif işlemi gerçekleştirilemedi.'};return data as any;}
  async createOffer(input:any){const {data,error}=await this.client().rpc('create_offer_thread',{p_actor_profile_id:input.actorProfileId,p_listing_id:input.listingId,p_amount:input.amount});return this.result(data,error);}
  async actOnOffer(input:any){const {data,error}=await this.client().rpc('act_on_offer_thread',{p_actor_profile_id:input.actorProfileId,p_thread_id:input.threadId,p_action:input.action,p_amount:input.amount??null});return this.result(data,error);}
  async listOffers({actorProfileId,box='received',status,cursor,limit=OFFER_PAGE_SIZE}:any){let q=this.client().from('offer_threads').select('*, listing:listings(id,public_id,title,price,status,offers_enabled,minimum_offer_amount,listing_images(*)), buyer:character_profiles!offer_threads_buyer_profile_id_fkey(id,full_name), seller:character_profiles!offer_threads_seller_profile_id_fkey(id,full_name)').eq(box==='sent'?'buyer_profile_id':'seller_profile_id',actorProfileId).order('updated_at',{ascending:false}).limit(Math.min(limit,OFFER_PAGE_SIZE));if(status)q=q.eq('status',status);if(cursor)q=q.lt('updated_at',cursor);const{data,error}=await q;if(error)throw new Error('Teklifler getirilemedi.');const threads=(data||[]).map((thread:any)=>({...thread,actor_side:thread.buyer_profile_id===actorProfileId?'BUYER':'SELLER'}));return{threads:threads as OfferThread[],nextCursor:data?.length===Math.min(limit,OFFER_PAGE_SIZE)?data.at(-1)?.updated_at:null};}
  async getOffer(threadId:string,actorProfileId:string){const{data,error}=await this.client().from('offer_threads').select('*, listing:listings(id,public_id,title,price,status,offers_enabled,minimum_offer_amount,listing_images(*)), buyer:character_profiles!offer_threads_buyer_profile_id_fkey(id,full_name), seller:character_profiles!offer_threads_seller_profile_id_fkey(id,full_name), events:offer_events(*)').eq('id',threadId).or(`buyer_profile_id.eq.${actorProfileId},seller_profile_id.eq.${actorProfileId}`).maybeSingle();if(error||!data)return{success:false,error:'Teklif bulunamadı.'};const thread={...data,actor_side:data.buyer_profile_id===actorProfileId?'BUYER':'SELLER',events:[...((data as any).events||[])].sort((a:any,b:any)=>a.created_at.localeCompare(b.created_at))};return{success:true,thread:thread as OfferThread};}
  async markRead(threadId:string,actorProfileId:string){const{data,error}=await this.client().rpc('mark_offer_thread_read',{p_actor_profile_id:actorProfileId,p_thread_id:threadId});return error?{success:false,unreadCount:0,error:'Okundu bilgisi güncellenemedi.'}:data;}
  async getUnreadCount(actorProfileId:string){const{data,error}=await this.client().rpc('get_offer_unread_count',{p_actor_profile_id:actorProfileId});if(error)return 0;return Number(data||0);}
  async getActiveCountForListing(listingId:string,actorProfileId:string){const{data,error}=await this.client().rpc('get_active_offer_count_for_listing',{p_listing_id:listingId,p_actor_profile_id:actorProfileId});if(error)return 0;return Number(data||0);}
  async expireStale(){const{data,error}=await this.client().rpc('expire_stale_offer_threads');if(error)return 0;return Number(data||0);}
  async closeForListing(listingId:string,reason:OfferCloseReason){const{data}=await this.client().rpc('close_offers_for_listing',{p_listing_id:listingId,p_reason:reason});return Number(data||0);}
  async recordListingPriceChange(listingId:string,oldPrice:number,newPrice:number){const{data}=await this.client().rpc('record_offer_listing_price_change',{p_listing_id:listingId,p_old_price:oldPrice,p_new_price:newPrice});return Number(data||0);}
}