import { IOfferRepository } from '../types';
import { getSupabaseAdminClient } from '../../supabase-client';
import { OFFER_PAGE_SIZE } from '@/lib/offers/constants';
import { OfferCloseReason, OfferThread } from '@/types';
import { redactPrivateContact } from '@/lib/profiles/contact-privacy';

const relations = 'listing:listings(id,public_id,title,price,status,offers_enabled,minimum_offer_amount,seller_type,corporate_profile_id,listing_images(*),corporate:corporate_profiles(phone,email)), buyer:character_profiles!offer_threads_buyer_profile_id_fkey(id,public_id,full_name,avatar_url,avatar_path,phone,sanmail_email,phone_visibility,sanmail_visibility), seller:character_profiles!offer_threads_seller_profile_id_fkey(id,public_id,full_name,avatar_url,avatar_path,phone,sanmail_email,phone_visibility,sanmail_visibility)';

export class SupabaseOfferRepository implements IOfferRepository {
  private client(){const c=getSupabaseAdminClient();if(!c)throw new Error('Supabase service role yapılandırılmamış.');return c;}
  private result(data:any,error:any){if(error)return{success:false,error:'Teklif işlemi gerçekleştirilemedi.'};return data as any;}
  private present(thread:any,actorProfileId:string,withContact=false):OfferThread {
    const side=thread.buyer_profile_id===actorProfileId?'BUYER':'SELLER';
    const events=[...(thread.events||[])].sort((a:any,b:any)=>a.created_at.localeCompare(b.created_at));
    const readAt=side==='BUYER'?thread.buyer_last_read_at:thread.seller_last_read_at;
    const corporate=Array.isArray(thread.listing?.corporate)?thread.listing.corporate[0]:thread.listing?.corporate;
    const contact=withContact&&thread.status==='ACCEPTED'?(thread.listing?.seller_type==='CORPORATE'&&corporate?{phone:corporate.phone||'',sanmail_email:corporate.email||''}:redactPrivateContact(thread.seller)):undefined;
    const safeProfile=(profile:any)=>profile?{id:profile.id,public_id:profile.public_id,full_name:profile.full_name,avatar_url:profile.avatar_url||'',avatar_path:profile.avatar_path||''}:undefined;
    const historicalListing=thread.listing||thread.listing_snapshot;
    return {...thread,listing:historicalListing,buyer:safeProfile(thread.buyer),seller:safeProfile(thread.seller),events,actor_side:side,unread_count:events.filter((event:any)=>event.actor_profile_id!==actorProfileId&&(!readAt||event.created_at>readAt)).length,visible_contact:contact?{phone:contact.phone,sanmail_email:contact.sanmail_email}:undefined};
  }
  async createOffer(input:any){const {data,error}=await this.client().rpc('create_offer_thread',{p_actor_profile_id:input.actorProfileId,p_listing_id:input.listingId,p_amount:input.amount});return this.result(data,error);}
  async actOnOffer(input:any){const {data,error}=await this.client().rpc('act_on_offer_thread',{p_actor_profile_id:input.actorProfileId,p_thread_id:input.threadId,p_action:input.action,p_amount:input.amount??null,p_proposal_event_id:input.proposalEventId??null});return this.result(data,error);}
  async listOffers({actorProfileId,box='received',status,cursor,limit=OFFER_PAGE_SIZE}:any){const side=box==='sent'?'buyer':'seller';let q=this.client().from('offer_threads').select(`*, ${relations}, events:offer_events(*)`).eq(`${side}_profile_id`,actorProfileId).is(`${side}_hidden_at`,null).order('updated_at',{ascending:false}).limit(Math.min(limit,OFFER_PAGE_SIZE));if(status)q=q.eq('status',status);if(cursor)q=q.lt('updated_at',cursor);const{data,error}=await q;if(error)throw new Error('Teklifler getirilemedi.');const threads=(data||[]).map((thread:any)=>this.present(thread,actorProfileId));return{threads,nextCursor:data?.length===Math.min(limit,OFFER_PAGE_SIZE)?data.at(-1)?.updated_at:null};}
  async getOffer(threadId:string,actorProfileId:string){const{data,error}=await this.client().from('offer_threads').select(`*, ${relations}, events:offer_events(*)`).eq('id',threadId).or(`buyer_profile_id.eq.${actorProfileId},seller_profile_id.eq.${actorProfileId}`).maybeSingle();const hidden=data&&(data.buyer_profile_id===actorProfileId?data.buyer_hidden_at:data.seller_hidden_at);if(error||!data||hidden)return{success:false,error:'Teklif bulunamadı.'};return{success:true,thread:this.present(data,actorProfileId,true)};}
  async getActiveThreadForListing(listingId:string,actorProfileId:string){const{data,error}=await this.client().from('offer_threads').select(`*, ${relations}, events:offer_events(*)`).eq('listing_id',listingId).eq('status','ACTIVE').or(`buyer_profile_id.eq.${actorProfileId},seller_profile_id.eq.${actorProfileId}`).maybeSingle();const hidden=data&&(data.buyer_profile_id===actorProfileId?data.buyer_hidden_at:data.seller_hidden_at);return error||!data||hidden?null:this.present(data,actorProfileId,true);}
  async markRead(threadId:string,actorProfileId:string){const{data,error}=await this.client().rpc('mark_offer_thread_read',{p_actor_profile_id:actorProfileId,p_thread_id:threadId});return error?{success:false,unreadCount:0,error:'Okundu bilgisi güncellenemedi.'}:data;}
  async markAllRead(actorProfileId:string,box:'received'|'sent'){const{data,error}=await this.client().rpc('mark_offer_box_read',{p_actor_profile_id:actorProfileId,p_box:box});if(error)return{success:false,count:0,unreadCounts:await this.getUnreadCounts(actorProfileId),error:'Okundu bilgileri güncellenemedi.'};const result=Array.isArray(data)?data[0]:data;return{success:Boolean(result?.success),count:Number(result?.count||0),unreadCounts:await this.getUnreadCounts(actorProfileId),error:result?.error||undefined};}
  async hideOffer(threadId:string,actorProfileId:string){const{data,error}=await this.client().rpc('hide_offer_thread',{p_actor_profile_id:actorProfileId,p_thread_id:threadId});return error?{success:false,unreadCount:0,error:'Teklif gizlenemedi.'}:data;}
  async getUnreadCount(actorProfileId:string){const{data,error}=await this.client().rpc('get_offer_unread_count',{p_actor_profile_id:actorProfileId});if(error)return 0;return Number(data||0);}
  async getUnreadCounts(actorProfileId:string){const{data,error}=await this.client().from('offer_threads').select('buyer_profile_id,seller_profile_id,buyer_last_read_at,seller_last_read_at,buyer_hidden_at,seller_hidden_at,events:offer_events(actor_profile_id,created_at)').or(`buyer_profile_id.eq.${actorProfileId},seller_profile_id.eq.${actorProfileId}`);if(error)return{total:0,received:0,sent:0};let received=0;let sent=0;for(const thread of data||[]){const buyer=thread.buyer_profile_id===actorProfileId;if((buyer&&thread.buyer_hidden_at)||(!buyer&&thread.seller_hidden_at))continue;const readAt=buyer?thread.buyer_last_read_at:thread.seller_last_read_at;const events=Array.isArray(thread.events)?thread.events:[];const count=events.filter((event:any)=>event.actor_profile_id!==actorProfileId&&(!readAt||event.created_at>readAt)).length;if(buyer)sent+=count;else received+=count;}return{total:received+sent,received,sent};}
  async getActiveCountForListing(listingId:string,actorProfileId:string){const{data,error}=await this.client().rpc('get_active_offer_count_for_listing',{p_listing_id:listingId,p_actor_profile_id:actorProfileId});if(error)return 0;return Number(data||0);}
  async expireStale(){const{data,error}=await this.client().rpc('expire_stale_offer_threads');if(error)return 0;return Number(data||0);}
  async closeForListing(listingId:string,reason:OfferCloseReason){const{data}=await this.client().rpc('close_offers_for_listing',{p_listing_id:listingId,p_reason:reason});return Number(data||0);}
  async recordListingPriceChange(listingId:string,oldPrice:number,newPrice:number){const{data}=await this.client().rpc('record_offer_listing_price_change',{p_listing_id:listingId,p_old_price:oldPrice,p_new_price:newPrice});return Number(data||0);}
}