'use client';
import { useEffect, useRef } from 'react';
import { Loader2, PauseCircle, PlayCircle } from 'lucide-react';
import type { Listing } from '@/types';
import { formatDurationSeconds, formatTimeRemaining } from '@/lib/utils/format';

export function ListingFreezeDialog({listing,corporate,busy,onCancel,onConfirm}:{listing:Listing;corporate:boolean;busy:boolean;onCancel:()=>void;onConfirm:()=>void}){
  const cancelRef=useRef<HTMLButtonElement>(null);const frozen=listing.status==='FROZEN';
  useEffect(()=>{cancelRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)onCancel();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[busy,onCancel]);
  const listingTime=frozen?formatDurationSeconds(listing.remaining_listing_seconds):formatTimeRemaining(listing.expires_at).text.replace(' kaldı','');
  const boostTime=frozen?formatDurationSeconds(listing.remaining_boost_seconds):listing.featured_until?formatTimeRemaining(listing.featured_until).text.replace(' kaldı',''):'Yok';
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget&&!busy)onCancel();}}><section role="dialog" aria-modal="true" aria-labelledby="listing-freeze-title" aria-describedby="listing-freeze-description" className="surface-card w-full max-w-md rounded-2xl border border-emerald-400/25 p-6 shadow-2xl"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-400/10 text-emerald-300">{frozen?<PlayCircle className="h-5 w-5"/>:<PauseCircle className="h-5 w-5"/>}</div><div><h3 id="listing-freeze-title" className="font-extrabold text-[var(--text-main)]">{frozen?'İlanı yeniden aktif etmek istediğine emin misin?':'İlanı dondurmak istediğine emin misin?'}</h3><p id="listing-freeze-description" className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{frozen?'İlanınız saklanan kalan süre üzerinden yeniden yayına alınacaktır.':corporate?'İlanı dondurursanız eğer, kalan ilan süresi ve varsa kalan öne çıkarma süresi üzerinden tekrardan ilanınızı aktif hâle getirebilirsiniz.':'İlanı dondurursanız eğer, kalan ilan süreniz üzerinden tekrardan ilanınızı aktif hâle getirebilirsiniz.'}</p></div></div><div className="mt-5 space-y-2 rounded-xl border border-[var(--border-app)] bg-[var(--bg-surface-secondary)] p-3 text-xs"><p className="flex justify-between gap-3"><span className="text-[var(--text-muted)]">Kalan ilan süresi:</span><strong>{listingTime}</strong></p>{corporate&&<p className="flex justify-between gap-3"><span className="text-[var(--text-muted)]">Kalan öne çıkarma:</span><strong>{boostTime}</strong></p>}</div><div className="mt-6 grid grid-cols-2 gap-3"><button ref={cancelRef} type="button" disabled={busy} onClick={onCancel} className="btn-secondary justify-center px-4 py-2.5 text-xs">Hayır</button><button type="button" disabled={busy} onClick={onConfirm} className="flex items-center justify-center gap-2 rounded-lg bg-emerald-500 px-4 py-2.5 text-xs font-black text-white hover:bg-emerald-400 disabled:opacity-60">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:'Evet'}</button></div></section></div>;
}